/* ================================
   Common
================================ */

typedef int API_TYPE;

#define API_TYPE_WIN 0
#define API_TYPE_MAC 1

/* ================================
   Configuration
================================ */

typedef int CONFIGURATION_GETRESULT;

#define CONFIGURATION_GETRESULT_OK 0

#define CONFIGURATION_GETRESULT_CANTCREATEWMSSDKINITIALIZER 1
#define CONFIGURATION_GETRESULT_CANTINITIALIZEWMSSDK 2
#define CONFIGURATION_GETRESULT_OLDWMSSDK 3
#define CONFIGURATION_GETRESULT_WMSSERVICEUNAVAILABLE 4
#define CONFIGURATION_GETRESULT_WMSUNKNOWNERROR 5

typedef int CONFIGURATION_CLEANUPRESULT;

#define CONFIGURATION_CLEANUPRESULT_OK 0

#define CONFIGURATION_CLEANUPRESULT_WMSUNKNOWNERROR 1

/* ================================
   High-precision tick generator
================================ */

typedef int TGSESSION_OPENRESULT;

#define TGSESSION_OPENRESULT_OK 0

#define TGSESSION_OPENRESULT_FAILEDTOGETTIMEBASEINFO 101
#define TGSESSION_OPENRESULT_FAILEDTOSETREALTIMEPRIORITY 102
#define TGSESSION_OPENRESULT_THREADSTARTERROR 103

typedef int TGSESSION_CLOSERESULT;

#define TGSESSION_CLOSERESULT_OK 0

#define TGSESSION_CLOSERESULT_THREADEXITTIMEOUT 101

typedef int TG_STARTRESULT;

#define TG_STARTRESULT_OK 0

#define TG_STARTRESULT_CANTGETDEVICECAPABILITIES 1
#define TG_STARTRESULT_CANTSETTIMERCALLBACK 2

#define TG_STARTRESULT_NORESOURCES 101
#define TG_STARTRESULT_BADTHREADATTRIBUTE 102
#define TG_STARTRESULT_UNKNOWNERROR 199

typedef int TG_STOPRESULT;

#define TG_STOPRESULT_OK 0

#define TG_STOPRESULT_CANTENDPERIOD 1
#define TG_STOPRESULT_CANTKILLEVENT 2

/* ================================
   Devices common
================================ */

typedef int GETSTRINGPROPERTYRESULT;

#define GETSTRINGPROPERTYRESULT_OK 0

#define GETSTRINGPROPERTYRESULT_PROPERTYUNAVAILABLE 100
#define GETSTRINGPROPERTYRESULT_FAILEDGETVALUE 101
#define GETSTRINGPROPERTYRESULT_FAILEDFILLVALUEBUFFER 102

typedef int DEVICE_GETDEVICEINFORESULT;

#define DEVICE_GETDEVICEINFORESULT_OK 0

#define DEVICE_GETDEVICEINFORESULT_FAILEDGETENDPOINTINFO 1
#define DEVICE_GETDEVICEINFORESULT_FAILEDGETPARENTDEVICEINFO 2
#define DEVICE_GETDEVICEINFORESULT_UNKNOWNWMSERROR 3
#define DEVICE_GETDEVICEINFORESULT_FAILEDPREPAREDEVICEINFO 4
#define DEVICE_GETDEVICEINFORESULT_FAILEDGETDEVICEINFO 5
#define DEVICE_GETDEVICEINFORESULT_FAILEDPREPAREPARENTDEVICEINFO 6

#define DEVICE_GETDEVICEINFORESULT_FAILEDGETENTITY 101
#define DEVICE_GETDEVICEINFORESULT_FAILEDGETDEVICE 102
#define DEVICE_GETDEVICEINFORESULT_FAILEDGETID 103

#define DEVICE_GETDEVICEINFORESULT_NAME_UNAVAILABLE 104
#define DEVICE_GETDEVICEINFORESULT_NAME_FAILEDGETVALUE 105
#define DEVICE_GETDEVICEINFORESULT_NAME_FAILEDFILLVALUEBUFFER 106

/* ================================
   Session
================================ */

typedef int SESSION_CALLBACKOPERATION;

#define SESSION_CALLBACKOPERATION_ENDPOINTADDED 0
#define SESSION_CALLBACKOPERATION_ENDPOINTREMOVED 1

typedef int SESSION_OPENRESULT;

#define SESSION_OPENRESULT_OK 0

#define SESSION_OPENRESULT_CANTCREATEWMSSDKINITIALIZER 1
#define SESSION_OPENRESULT_CANTINITIALIZEWMSSDK 2
#define SESSION_OPENRESULT_OLDWMSSDK 3
#define SESSION_OPENRESULT_WMSSERVICEUNAVAILABLE 4
#define SESSION_OPENRESULT_WMSUNKNOWNERROR 5

#define SESSION_OPENRESULT_SERVERSTARTERROR 101
#define SESSION_OPENRESULT_WRONGTHREAD 102
#define SESSION_OPENRESULT_NOTPERMITTED 103
#define SESSION_OPENRESULT_UNKNOWNERROR 104
#define SESSION_OPENRESULT_THREADSTARTERROR 105
#define SESSION_OPENRESULT_CLIENTCREATIONTIMEOUT 106

typedef int SESSION_CLOSERESULT;

#define SESSION_CLOSERESULT_OK 0

#define SESSION_CLOSERESULT_THREADEXITTIMEOUT 101

/* ================================
   Input device
================================ */

typedef int IN_GETCOUNTRESULT;

#define IN_GETCOUNTRESULT_OK 0

typedef int IN_GETINFORESULT;

#define IN_GETINFORESULT_OK 0

#define IN_GETINFORESULT_BADDEVICEID 1
#define IN_GETINFORESULT_INVALIDSTRUCTURE 2
#define IN_GETINFORESULT_NODRIVER 3
#define IN_GETINFORESULT_NOMEMORY 4

#define IN_GETINFORESULT_UNKNOWNERROR 1000

typedef int IN_GETALLINFORESULT;

#define IN_GETALLINFORESULT_OK 0

#define IN_GETALLINFORESULT_BADDEVICEID 1
#define IN_GETALLINFORESULT_INVALIDSTRUCTURE 2
#define IN_GETALLINFORESULT_NODRIVER 3
#define IN_GETALLINFORESULT_NOMEMORY 4
#define IN_GETALLINFORESULT_UNKNOWNWMSERROR 5

#define IN_GETALLINFORESULT_UNKNOWNERROR 1000
#define IN_GETALLINFORESULT_UNKNOWNERRORONGETINFO 1001

typedef int IN_OPENRESULT;

#define IN_OPENRESULT_OK 0

#define IN_OPENRESULT_ALLOCATED 1
#define IN_OPENRESULT_BADDEVICEID 2
#define IN_OPENRESULT_INVALIDFLAG 3
#define IN_OPENRESULT_INVALIDSTRUCTURE 4
#define IN_OPENRESULT_NOMEMORY 5
#define IN_OPENRESULT_FAILEDPREPARESYSEXBUFFERS 6

#define IN_OPENRESULT_GETCONNECTION_OPENFAILED 7
#define IN_OPENRESULT_GETCONNECTION_UNKNOWNERROR 8
#define IN_OPENRESULT_UNKNOWNWMSERROR 9

#define IN_OPENRESULT_INVALIDCLIENT 101
#define IN_OPENRESULT_INVALIDPORT 102
#define IN_OPENRESULT_WRONGTHREAD 103
#define IN_OPENRESULT_NOTPERMITTED 104

#define IN_OPENRESULT_UNKNOWNERROR 10000

typedef int IN_CLOSERESULT;

#define IN_CLOSERESULT_OK 0

#define IN_CLOSERESULT_RESET_INVALIDHANDLE 1
#define IN_CLOSERESULT_RESET_UNKNOWNERROR 3000

#define IN_CLOSERESULT_CLOSE_STILLPLAYING 2
#define IN_CLOSERESULT_CLOSE_INVALIDHANDLE 3
#define IN_CLOSERESULT_CLOSE_NOMEMORY 4
#define IN_CLOSERESULT_CLOSE_UNKNOWNERROR 2000

#define IN_CLOSERESULT_UNPREPAREBUFFER_STILLPLAYING 5
#define IN_CLOSERESULT_UNPREPAREBUFFER_INVALIDSTRUCTURE 6
#define IN_CLOSERESULT_UNPREPAREBUFFER_INVALIDHANDLE 7
#define IN_CLOSERESULT_UNPREPAREBUFFER_UNKNOWNERROR 1000

#define IN_CLOSERESULT_UNKNOWNWMSERROR 8

typedef int IN_RENEWSYSEXBUFFERRESULT;

#define IN_RENEWSYSEXBUFFERRESULT_OK 0

#define IN_RENEWSYSEXBUFFERRESULT_INVALIDHEADER 1
#define IN_RENEWSYSEXBUFFERRESULT_BUFFERNOTDONE 2
#define IN_RENEWSYSEXBUFFERRESULT_STILLPLAYING 3
#define IN_RENEWSYSEXBUFFERRESULT_UNPREPARED 4
#define IN_RENEWSYSEXBUFFERRESULT_INVALIDHANDLE 5
#define IN_RENEWSYSEXBUFFERRESULT_INVALIDSTRUCTURE 6
#define IN_RENEWSYSEXBUFFERRESULT_NOMEMORY 7
#define IN_RENEWSYSEXBUFFERRESULT_UNKNOWNERROR 8
#define IN_RENEWSYSEXBUFFERRESULT_CLOSING 9

typedef int IN_CONNECTRESULT;

#define IN_CONNECTRESULT_OK 0

#define IN_CONNECTRESULT_INVALIDHANDLE 1

#define IN_CONNECTRESULT_UNKNOWNERROR 101
#define IN_CONNECTRESULT_INVALIDPORT 102
#define IN_CONNECTRESULT_WRONGTHREAD 103
#define IN_CONNECTRESULT_NOTPERMITTED 104
#define IN_CONNECTRESULT_UNKNOWNENDPOINT 105
#define IN_CONNECTRESULT_WRONGENDPOINT 106

typedef int IN_DISCONNECTRESULT;

#define IN_DISCONNECTRESULT_OK 0

#define IN_DISCONNECTRESULT_INVALIDHANDLE 1

#define IN_DISCONNECTRESULT_UNKNOWNERROR 101
#define IN_DISCONNECTRESULT_INVALIDPORT 102
#define IN_DISCONNECTRESULT_WRONGTHREAD 103
#define IN_DISCONNECTRESULT_NOTPERMITTED 104
#define IN_DISCONNECTRESULT_UNKNOWNENDPOINT 105
#define IN_DISCONNECTRESULT_WRONGENDPOINT 106
#define IN_DISCONNECTRESULT_NOCONNECTION 107

typedef int IN_GETEVENTDATARESULT;

#define IN_GETEVENTDATARESULT_OK 0

typedef int IN_GETSYSEXDATARESULT;

#define IN_GETSYSEXDATARESULT_OK 0

typedef int IN_GETPROPERTYRESULT;

#define IN_GETPROPERTYRESULT_OK 0

#define IN_GETPROPERTYRESULT_PROPERTYUNAVAILABLE 101
#define IN_GETPROPERTYRESULT_FAILEDGETVALUE 102
#define IN_GETPROPERTYRESULT_FAILEDFILLVALUEBUFFER 103

typedef int IN_PREPARESYSEXBUFFERRESULT;

#define IN_PREPARESYSEXBUFFERRESULT_OK 0

#define IN_PREPARESYSEXBUFFERRESULT_PREPAREFAILED 1
#define IN_PREPARESYSEXBUFFERRESULT_ADDBUFFERFAILED 2

/* ================================
   Output device
================================ */

typedef int OUT_GETCOUNTRESULT;

#define OUT_GETCOUNTRESULT_OK 0

typedef int OUT_GETINFORESULT;

#define OUT_GETINFORESULT_OK 0

#define OUT_GETINFORESULT_BADDEVICEID 1
#define OUT_GETINFORESULT_INVALIDSTRUCTURE 2
#define OUT_GETINFORESULT_NODRIVER 3
#define OUT_GETINFORESULT_NOMEMORY 4
#define OUT_GETINFORESULT_UNKNOWNERROR 1000

typedef int OUT_GETALLINFORESULT;

#define OUT_GETALLINFORESULT_OK 0

#define OUT_GETALLINFORESULT_BADDEVICEID 1
#define OUT_GETALLINFORESULT_INVALIDSTRUCTURE 2
#define OUT_GETALLINFORESULT_NODRIVER 3
#define OUT_GETALLINFORESULT_NOMEMORY 4
#define OUT_GETALLINFORESULT_UNKNOWNWMSERROR 5

#define OUT_GETALLINFORESULT_UNKNOWNERROR 1000
#define OUT_GETALLINFORESULT_UNKNOWNERRORONGETINFO 1001

typedef int OUT_OPENRESULT;

#define OUT_OPENRESULT_OK 0

#define OUT_OPENRESULT_ALLOCATED 1
#define OUT_OPENRESULT_BADDEVICEID 2
#define OUT_OPENRESULT_INVALIDFLAG 3
#define OUT_OPENRESULT_INVALIDSTRUCTURE 4
#define OUT_OPENRESULT_NOMEMORY 5

#define OUT_OPENRESULT_GETCONNECTION_OPENFAILED 6
#define OUT_OPENRESULT_GETCONNECTION_UNKNOWNERROR 7
#define OUT_OPENRESULT_UNKNOWNWMSERROR 8

#define OUT_OPENRESULT_INVALIDCLIENT 101
#define OUT_OPENRESULT_INVALIDPORT 102
#define OUT_OPENRESULT_WRONGTHREAD 103
#define OUT_OPENRESULT_NOTPERMITTED 104
#define OUT_OPENRESULT_UNKNOWNERROR 105

typedef int OUT_CLOSERESULT;

#define OUT_CLOSERESULT_OK 0

#define OUT_CLOSERESULT_RESET_INVALIDHANDLE 1
#define OUT_CLOSERESULT_RESET_UNKNOWNERROR 1000
#define OUT_CLOSERESULT_CLOSE_STILLPLAYING 2
#define OUT_CLOSERESULT_CLOSE_INVALIDHANDLE 3
#define OUT_CLOSERESULT_CLOSE_NOMEMORY 4
#define OUT_CLOSERESULT_CLOSE_UNKNOWNERROR 2000
#define OUT_CLOSERESULT_UNKNOWNWMSERROR 5

typedef int OUT_SENDSHORTRESULT;

#define OUT_SENDSHORTRESULT_OK 0

#define OUT_SENDSHORTRESULT_BADOPENMODE 1
#define OUT_SENDSHORTRESULT_NOTREADY 2
#define OUT_SENDSHORTRESULT_INVALIDHANDLE 3
#define OUT_SENDSHORTRESULT_SENDERROR 4
#define OUT_SENDSHORTRESULT_UNKNOWNWMSERROR 5

#define OUT_SENDSHORTRESULT_INVALIDCLIENT 101
#define OUT_SENDSHORTRESULT_INVALIDPORT 102
#define OUT_SENDSHORTRESULT_WRONGENDPOINT 103
#define OUT_SENDSHORTRESULT_UNKNOWNENDPOINT 104
#define OUT_SENDSHORTRESULT_COMMUNICATIONERROR 105
#define OUT_SENDSHORTRESULT_SERVERSTARTERROR 106
#define OUT_SENDSHORTRESULT_WRONGTHREAD 107
#define OUT_SENDSHORTRESULT_NOTPERMITTED 108
#define OUT_SENDSHORTRESULT_UNKNOWNERROR 109

typedef int OUT_SENDSYSEXRESULT;

#define OUT_SENDSYSEXRESULT_OK 0

#define OUT_SENDSYSEXRESULT_PREPAREBUFFER_INVALIDHANDLE 1
#define OUT_SENDSYSEXRESULT_PREPAREBUFFER_INVALIDADDRESS 2
#define OUT_SENDSYSEXRESULT_PREPAREBUFFER_NOMEMORY 3
#define OUT_SENDSYSEXRESULT_PREPAREBUFFER_UNKNOWNERROR 1000
#define OUT_SENDSYSEXRESULT_NOTREADY 4
#define OUT_SENDSYSEXRESULT_UNPREPARED 5
#define OUT_SENDSYSEXRESULT_INVALIDHANDLE 6
#define OUT_SENDSYSEXRESULT_INVALIDSTRUCTURE 7
#define OUT_SENDSYSEXRESULT_SENDERROR 8
#define OUT_SENDSYSEXRESULT_UNKNOWNWMSERROR 9

#define OUT_SENDSYSEXRESULT_INVALIDCLIENT 101
#define OUT_SENDSYSEXRESULT_INVALIDPORT 102
#define OUT_SENDSYSEXRESULT_WRONGENDPOINT 103
#define OUT_SENDSYSEXRESULT_UNKNOWNENDPOINT 104
#define OUT_SENDSYSEXRESULT_COMMUNICATIONERROR 105
#define OUT_SENDSYSEXRESULT_SERVERSTARTERROR 106
#define OUT_SENDSYSEXRESULT_WRONGTHREAD 107
#define OUT_SENDSYSEXRESULT_NOTPERMITTED 108
#define OUT_SENDSYSEXRESULT_UNKNOWNERROR 109

typedef int OUT_GETSYSEXDATARESULT;

#define OUT_GETSYSEXDATARESULT_OK 0

#define OUT_GETSYSEXDATARESULT_STILLPLAYING 1
#define OUT_GETSYSEXDATARESULT_INVALIDSTRUCTURE 2
#define OUT_GETSYSEXDATARESULT_INVALIDHANDLE 3
#define OUT_GETSYSEXDATARESULT_UNKNOWNERROR 1000

typedef int OUT_GETPROPERTYRESULT;

#define OUT_GETPROPERTYRESULT_OK 0

#define OUT_GETPROPERTYRESULT_PROPERTYUNAVAILABLE 101
#define OUT_GETPROPERTYRESULT_FAILEDGETVALUE 102
#define OUT_GETPROPERTYRESULT_FAILEDFILLVALUEBUFFER 103

/* ================================
 Virtual device
 ================================ */
 
typedef int VIRTUAL_OPENRESULT;
 
#define VIRTUAL_OPENRESULT_OK 0

#define VIRTUAL_OPENRESULT_WMSUNAVAILABLE 1
#define VIRTUAL_OPENRESULT_WMSBASICLOOPBACKUNAVAILABLE 2
#define VIRTUAL_OPENRESULT_FAILED 3
#define VIRTUAL_OPENRESULT_FAILEDGETINPUTDEVICEINFO 4
#define VIRTUAL_OPENRESULT_FAILEDGETOUTPUTDEVICEINFO 5
#define VIRTUAL_OPENRESULT_WMSERROR 6
#define VIRTUAL_OPENRESULT_CLIENTAPIEXCEPTION 7
#define VIRTUAL_OPENRESULT_INVALIDUNIQUEID 8
#define VIRTUAL_OPENRESULT_DUPLICATEENDPOINTNAME 9
#define VIRTUAL_OPENRESULT_DUPLICATEUNIQUEID 10
#define VIRTUAL_OPENRESULT_ENDPOINTCREATIONFAILED 11
#define VIRTUAL_OPENRESULT_ENDPOINTNOTFOUND 12
#define VIRTUAL_OPENRESULT_INVALIDARGUMENT 13
#define VIRTUAL_OPENRESULT_INVALIDJSON 14
#define VIRTUAL_OPENRESULT_INVALIDORMISSINGASSOCIATIONID 15
#define VIRTUAL_OPENRESULT_INVALIDORMISSINGENDPOINTNAME 16
#define VIRTUAL_OPENRESULT_UNRECOGNIZEDCOMMAND 17

#define VIRTUAL_OPENRESULT_CREATESOURCE_NOTPERMITTED 101
#define VIRTUAL_OPENRESULT_CREATESOURCE_SERVERSTARTERROR 102
#define VIRTUAL_OPENRESULT_CREATESOURCE_WRONGTHREAD 103
#define VIRTUAL_OPENRESULT_CREATESOURCE_UNKNOWNERROR 104
#define VIRTUAL_OPENRESULT_CREATEDESTINATION_NOTPERMITTED 105
#define VIRTUAL_OPENRESULT_CREATEDESTINATION_SERVERSTARTERROR 106
#define VIRTUAL_OPENRESULT_CREATEDESTINATION_WRONGTHREAD 107
#define VIRTUAL_OPENRESULT_CREATEDESTINATION_UNKNOWNERROR 108
#define VIRTUAL_OPENRESULT_CREATESOURCE_FAILEDPROCESSNAME 109
#define VIRTUAL_OPENRESULT_CREATEDESTINATION_FAILEDPROCESSNAME 110

typedef int VIRTUAL_CLOSERESULT;
 
#define VIRTUAL_CLOSERESULT_OK 0

#define VIRTUAL_CLOSERESULT_FAILED 1
#define VIRTUAL_CLOSERESULT_WMSERROR 2

#define VIRTUAL_CLOSERESULT_DISPOSESOURCE_UNKNOWNENDPOINT 101
#define VIRTUAL_CLOSERESULT_DISPOSESOURCE_NOTPERMITTED 102
#define VIRTUAL_CLOSERESULT_DISPOSESOURCE_UNKNOWNERROR 103
#define VIRTUAL_CLOSERESULT_DISPOSEDESTINATION_UNKNOWNENDPOINT 104
#define VIRTUAL_CLOSERESULT_DISPOSEDESTINATION_NOTPERMITTED 105
#define VIRTUAL_CLOSERESULT_DISPOSEDESTINATION_UNKNOWNERROR 106

typedef int VIRTUAL_SENDBACKRESULT;
 
#define VIRTUAL_SENDBACKRESULT_OK 0

#define VIRTUAL_SENDBACKRESULT_UNKNOWNENDPOINT 101
#define VIRTUAL_SENDBACKRESULT_WRONGENDPOINT 102
#define VIRTUAL_SENDBACKRESULT_NOTPERMITTED 103
#define VIRTUAL_SENDBACKRESULT_SERVERSTARTERROR 104
#define VIRTUAL_SENDBACKRESULT_WRONGTHREAD 105
#define VIRTUAL_SENDBACKRESULT_UNKNOWNERROR 106
#define VIRTUAL_SENDBACKRESULT_MESSAGESENDERROR 107

typedef int VIRTUAL_MUTERESULT;

#define VIRTUAL_MUTERESULT_OK 0

#define VIRTUAL_MUTERESULT_FAILED 1
#define VIRTUAL_MUTERESULT_WMSERROR 2

typedef int VIRTUAL_UNMUTERESULT;

#define VIRTUAL_UNMUTERESULT_OK 0

#define VIRTUAL_UNMUTERESULT_FAILED 1
#define VIRTUAL_UNMUTERESULT_WMSERROR 2