stages:
- stage: BuildNativeLibs
  displayName: Build native libraries
  jobs:
  - job: BuildDll64
    displayName: 'Build 64-bit dll'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      displayName: 'Build dll'
      inputs:
        targetType: 'inline'
        script: |
          cd Resources\Native
          Write-Host "Step 1"
          gcc -c NativeApi-Windows.cpp -lwinmm -lstdc++
          Write-Host "Step 2"
          gcc -shared -o Melanchall_DryWetMidi_Native64.dll NativeApi-Windows.o -lwinmm -lstdc++
    - task: PublishPipelineArtifact@1
      displayName: 'Publish dll artifact'
      inputs:
        targetPath: 'Resources\Native\Melanchall_DryWetMidi_Native64.dll'
        artifactName: 'Melanchall_DryWetMidi_Native64.dll'
        artifactType: pipeline
  - job: BuildDylib64
    displayName: 'Build 64-bit dylib'
    pool:
      vmImage: 'macos-latest'
    steps:
    - task: PowerShell@2
      displayName: 'Build dylib'
      inputs:
        targetType: 'inline'
        script: |
          cd Resources/Native
          Write-Host "Building arm64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native64_arm64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch arm64
          Write-Host "Building x86_64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native64_x86_64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch x86_64
          Write-Host "Merging dylibs into single unversal one..."
          lipo Melanchall_DryWetMidi_Native64_x86_64.dylib Melanchall_DryWetMidi_Native64_arm64.dylib -output Melanchall_DryWetMidi_Native64.dylib -create
          lipo -info Melanchall_DryWetMidi_Native64.dylib
    - task: PublishPipelineArtifact@1
      displayName: 'Publish dylib artifact'
      inputs:
        targetPath: 'Resources/Native/Melanchall_DryWetMidi_Native64.dylib'
        artifactName: 'Melanchall_DryWetMidi_Native64.dylib'
        artifactType: pipeline