<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net7.0;net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>11</LangVersion>
    <Configurations>Debug;Release;ReleaseTest;ReleaseTestFull;ReleaseNativeless;DebugNativeless</Configurations>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL2087;IL2091;IL3050;IL3051;IL2027;IL2072;IL2075</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <PackageId>Melanchall.DryWetMidi</PackageId>
    <Version>0.0.0</Version>
    <Authors>melanchall</Authors>
    <Owners>melanchall</Owners>
    <licenseUrl>https://github.com/melanchall/drywetmidi/blob/master/LICENSE</licenseUrl>
    <PackageProjectUrl>https://github.com/melanchall/drywetmidi</PackageProjectUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/melanchall/drywetmidi/master/Resources/NuGet/icon.png</PackageIconUrl>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/melanchall/drywetmidi</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/melanchall/drywetmidi/releases/tag/v0.0.0</PackageReleaseNotes>
    <Description>
      DryWetMIDI is the .NET library to work with MIDI files and MIDI devices. It allows:

      * Read, write and create Standard MIDI Files (SMF). It is also possible to read RMID files where SMF wrapped to RIFF chunk.
      * Work with MIDI devices: send/receive MIDI data, play back and record MIDI data.
      * Finely adjust process of reading and writing. It allows, for example, to read corrupted files and repair them, or build MIDI file validators.
      * Implement custom meta events and custom chunks that can be write to and read from MIDI files.
      * Manage MIDI data either with low-level objects, like event, or high-level ones, like note.
      * Build musical compositions.
      * Perform complex musical tasks like quantizing, notes splitting or converting MIDI files to CSV.
    </Description>
    <Copyright>Copyright © Melanchall 0000</Copyright>
    <PackageTags>midi smf music composing notes chords device playback record</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>strongnamekey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG;TRACE;TEST;FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='DebugNativeless'">
    <DefineConstants>DEBUG;TRACE;TEST;NATIVELESS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseNativeless'">
    <DefineConstants>NATIVELESS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseTest'">
    <DefineConstants>TEST;FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseTestFull'">
    <DefineConstants>TRACE;TEST;FULL</DefineConstants>
  </PropertyGroup>

  <ItemGroup Label="Native">
    <None Include="..\Native\win_x64\Melanchall_DryWetMidi_Native.dll" Pack="true" PackagePath="runtimes/win-x64/native" />
    <None Include="..\Native\win_arm64\Melanchall_DryWetMidi_Native.dll" Pack="true" PackagePath="runtimes/win-arm64/native" />
    <None Include="..\Native\macos_x64_arm64\Melanchall_DryWetMidi_Native.dylib" Pack="true" PackagePath="build\" />
    <None Include="Melanchall.DryWetMidi.targets" Pack="true" PackagePath="build\" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='ReleaseNativeless' OR '$(Configuration)'=='DebugNativeless'">
    <Compile Remove="Multimedia\VirtualDevice\**\*.cs" />
    <Compile Remove="Multimedia\EndpointsWatcher\**\*.cs" />
    <Compile Remove="Multimedia\Session\**\*.cs" />
    <Compile Remove="Multimedia\Common\**\*.cs" />
    <Compile Remove="Common\Native\**\*.cs" />
    <Compile Remove="Multimedia\Device\**\*.cs" />
    <Compile Remove="Multimedia\Endpoint\**\*.cs" />
    <Compile Remove="Configuration\MidiConfigurationApi.cs" />
    <Compile Remove="Configuration\MidiConfiguration.cs" />
    <Compile Remove="Configuration\MidiConfigurationCheckpointNames.cs" />
    <Compile Remove="Configuration\MidiConfigurationHandle.cs" />
    <Compile Remove="Configuration\LibraryActivityMessageReceivedEventArgs.cs" />
    <Compile Remove="Multimedia\MidiDevice.cs" />
    <Compile Remove="Multimedia\MidiDeviceUtilities.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpoint.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpointHandle.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpointInfo.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpointApi.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpointCheckpointsNames.cs" />
    <Compile Remove="Multimedia\InputEndpoint\InputEndpointProperty.cs" />
    <Compile Remove="Multimedia\InputEndpoint\MidiTimeCodeReceivedEventArgs.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpoint.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointHandle.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointInfo.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointApi.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointCheckpointsNames.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointOption.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointProperty.cs" />
    <Compile Remove="Multimedia\OutputEndpoint\OutputEndpointTechnology.cs" />
    <Compile Remove="Multimedia\Clock\TickGenerator\Session\**\*.cs" />
    <Compile Remove="Multimedia\Clock\TickGenerator\TickGeneratorApi.cs" />
    <Compile Remove="Multimedia\Clock\TickGenerator\TickGeneratorUtilities.cs" />
    <Compile Remove="Multimedia\Clock\TickGenerator\TickGeneratorException.cs" />
    <Compile Remove="Multimedia\Clock\TickGenerator\HighPrecisionTickGenerator.cs" />
    <Compile Remove="Multimedia\ErrorOccurredEventArgs.cs" />
  </ItemGroup>

  <ItemGroup Label="Resources">
    <None Include="..\Resources\NuGet\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
