name: 'Copy native libraries locally'
description: 'Downloads and copies native libraries near csproj files'

inputs:
  win-arch:
    description:  'Windows dll architecture'
    type: string
    default: 'x64'
  macos-arch:
    description: 'macOS dylib architecture'
    type: string
    default: 'x64_arm64'

runs:
  using: 'composite'
  steps:
    - name: Download native libraries
      uses: actions/download-artifact@v4
      with:
        pattern: Native_*
        path: ${{ runner.temp }}/NativeLibraries
        merge-multiple: false
    
    - name: Copy native libraries locally
      shell: pwsh
      run: |
        & "${{ github.workspace }}/Resources/Scripts/Copy native binaries locally.ps1" -fromDirectory "${{ runner.temp }}/NativeLibraries"