name: 'Create MIDI Ports (Windows)'
description: 'Creates virtual MIDI ports on Windows'

inputs:
  enabled:
    description: 'Whether to run this action'
    required: false
    default: 'true'
  ports-names: 
    description: 'Comma-separated list of port names'
    required: false
    default: 'MIDI A,MIDI B,MIDI C'
  arch: 
    description: 'Utility architecture'
    required: false
    default: 'x64'

runs:
  using:  'composite'
  steps: 
    - name:  Ensure MIDI is ready (Windows)
      if: inputs.enabled == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        $service = Get-Service -Name "Audiosrv"
        
        if ($service.Status -ne 'Running')
        {
          Write-Host "Service is not started; starting..."
          Start-Service "Audiosrv"
        }
        
        Write-Host "Service is started"
    
    - name: Create virtual MIDI ports (Windows)
      if: inputs.enabled == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        & "${{ github.workspace }}/Resources/Scripts/Setup MIDI ports.ps1" -portsNames "${{ inputs.ports-names }}" -arch "${{ inputs.arch }}"