trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/CI/build-artifacts-library.yaml'
    - 'Resources/CI/Templates/stage-build-native-libs.yaml'
    - 'Resources/CI/Templates/step-copy-native-libraries-near-csproj.yaml'
    - 'Resources/CI/Templates/job-build-package.yaml'
    - 'Resources/CI/Templates/step-build-docs.yaml'
    - 'Resources/CI/Templates/step-generate-doc-links.yaml'
    - 'Resources/Native/*'

pr: none

variables:
- group: DryWetMIDI-Common-Variables

name: BuildLibrary_$(SourceBranchName)_$(LibraryVersion)$(Rev:.r)

stages:
- template: Templates/stage-build-native-libs.yaml
- stage: BuildBinaries
  displayName: Build binaries
  pool:
    vmImage: 'windows-latest'
  jobs:
  - template: Templates/job-build-package.yaml
    parameters:
      packageType: 'Full'
  - job: BuildBinaries
    displayName: Build binaries
    steps:
    - template: Templates/step-setup-framework.yaml
      parameters:
        framework: 'Net'
    
    - template: Templates/step-generate-doc-links.yaml
    
    - template: Templates/step-copy-native-libraries-near-csproj.yaml
    
    - template: Templates/step-generate-obsolete-api-hints.yaml
    
    - task: DotNetCoreCLI@2
      displayName: Build project
      inputs:
        command: 'build'
        projects: 'DryWetMidi/Melanchall.DryWetMidi.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    
    - task: PowerShell@2
      displayName: Delete pdb files
      inputs:
        targetType: 'inline'
        script: |
          Get-ChildItem $(Build.SourcesDirectory) -Include *.pdb -Recurse | Remove-Item -Force
    
    - ${{ each tfm in split('netstandard2.0,net7.0,net8.0', ',') }}:
      - task: ArchiveFiles@2
        displayName: Archive binaries (${{ tfm }})
        inputs:
          rootFolderOrFile: 'DryWetMidi\bin\$(BuildConfiguration)\${{ tfm }}'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)\Binaries\DryWetMIDI.$(LibraryVersion)-bin-${{ tfm }}.zip'
        
    - task: PowerShell@2
      displayName: Copy native binaries in directory
      inputs:
        targetType: 'inline'
        script: |
          $winX64Destination = "$(Pipeline.Workspace)/Native/win_x64"
          New-Item -ItemType Directory -Force -Path $winX64Destination
          Copy-Item -Path "$(Pipeline.Workspace)/NativeLibraries/Native_Win_x64/Melanchall_DryWetMidi_Native.dll" -Destination "$winX64Destination" -Force -Verbose
          
          $winArm64Destination = "$(Pipeline.Workspace)/Native/win_arm64"
          New-Item -ItemType Directory -Force -Path $winArm64Destination
          Copy-Item -Path "$(Pipeline.Workspace)/NativeLibraries/Native_Win_arm64/Melanchall_DryWetMidi_Native.dll" -Destination "$winArm64Destination" -Force -Verbose
          
          $macosX64Arm64Destination = "$(Pipeline.Workspace)/Native/macos_x64_arm64"
          New-Item -ItemType Directory -Force -Path $macosX64Arm64Destination
          Copy-Item -Path "$(Pipeline.Workspace)/NativeLibraries/Native_macOS_x64_arm64/Melanchall_DryWetMidi_Native.dylib" -Destination "$macosX64Arm64Destination" -Force -Verbose
    
    - task: ArchiveFiles@2
      displayName: Archive native binaries
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)\Native'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)\Binaries\DryWetMIDI.$(LibraryVersion)-bin-native.zip'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish 'Binaries' artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)\Binaries
        artifact: Binaries