trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Docs/*'
    - 'Resources/CI/build-artifacts-docs.yaml'
    - 'Resources/CI/Templates/step-build-docs.yaml'
    - 'README.md'

pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: DryWetMIDI-Common-Variables

name: BuildDocs_$(SourceBranchName)_$(LibraryVersion)$(Rev:.r)

steps:
- template: Templates/step-generate-obsolete-api-hints.yaml

- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: 'DryWetMidi/Melanchall.DryWetMidi.csproj'

- template: Templates/step-execute-ci-tool.yaml
  parameters:
    tool: 'SetupDocs'
    toolArguments: '"README.md" "Docs"'

- template: Templates/step-execute-ci-tool.yaml
  parameters:
    tool: 'GenerateDocsObsoleteApiSection'
    toolArguments: '"Docs\obsolete"'

- template: Templates/step-build-docs.yaml

- template: Templates/step-execute-ci-tool.yaml
  parameters:
    tool: 'AddGoogleAnalyticsTagForDocs'
    toolArguments: '"$(GoogleAnalytics.MeasurementId.Docs)" "Docs/_site"'

- task: PublishPipelineArtifact@1
  displayName: Publish 'Docs' artifact
  inputs:
    targetPath: 'Docs\_site'
    artifact: Docs
    
- task: PublishPipelineArtifact@1
  displayName: Publish 'docfx.json' artifact
  inputs:
    targetPath: 'Docs\docfx.json'
    artifact: docfx.json