trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - DryWetMidi.Benchmarks/
    - DryWetMidi.Tests/
    - Resources/CI/win-test-netframework-core.yaml
    - Resources/CI/win-test-netframework-devices.yaml
    - Resources/CI/mac-test-netcore-core.yaml
    - Resources/CI/benchmarks-develop-win.yaml
    - Resources/CI/build-artifacts-library.yaml
    - Resources/CI/check-readme-links.yaml
    - .github/

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.1.0'

name: $(TeamProject)_$(SourceBranchName)_BuildDocs_$(version)$(Rev:.r)

steps:
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: PowerShell@2
  displayName: Setup docs pages
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Writing build datetime to site footer..."
      $content = Get-Content -Path Docs\docfx.json -Raw
      $currentDateTime = Get-Date -Format "MMMM d, yyyy HH:mm:ss"
      $content = $content -Replace "{BUILD_DATETIME}",$currentDateTime
      Set-Content -Path Docs\docfx.json -Value $content
      
      Write-Host "Copying README.md as index.md to Docs folder..."
      Copy-Item README.md -Destination Docs\index.md

- task: PowerShell@2
  displayName: Install docfx
  inputs:
    targetType: 'inline'
    script: choco install docfx -y
      
- task: PowerShell@2
  displayName: Build docs
  inputs:
    targetType: 'inline'
    script: docfx Docs/docfx.json

- task: PublishPipelineArtifact@1
  displayName: Publish 'Docs' artifact
  inputs:
    targetPath: Docs\_site
    artifact: Docs

- task: PublishPipelineArtifact@1
  displayName: Publish 'LatestReleaseNotes' artifact
  inputs:
    targetPath: Docs\latest-release-notes.md
    artifact: LatestReleaseNotes

- task: PowerShell@2
  displayName: Prepare release notes for midi.org
  inputs:
    targetType: 'inline'
    script: |
      $content = Get-Content Docs\latest-release-notes.md
      $content = $content `
        -Replace '\[`?(.+?)`?\]\(.+?\)', '[i]$1[/i]' `
        -Replace '# (.+?)$', '[u]$1[/u]' `
        -Replace '\*\*(.+?)\*\*', '[b]$1[/b]' `
        -Replace '`(.+?)`', '[i]$1[/i]' `
        -Replace '^\*', '[*]' `
        -Replace '^  \*', '  -'
      Set-Content -Path "Docs\latest-release-notes-midi-org.txt" -Value $content

- task: PublishPipelineArtifact@1
  displayName: Publish 'LatestReleaseNotesMidiOrg' artifact
  inputs:
    targetPath: Docs\latest-release-notes-midi-org.txt
    artifact: LatestReleaseNotesMidiOrg