trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/Utilities/CheckLinks/*'
    - 'Resources/CI/check-cs-links.yaml'

pr:
  branches:
    include:
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/Utilities/CheckLinks/*'
    - 'Resources/CI/check-cs-links.yaml'

schedules:
- cron: '0 0,9,15,20 * * *'
  displayName: Check cs links schedule
  branches:
    include:
    - master
    - develop
  always: 'true'

pool:
  vmImage: 'windows-latest'

name: CheckCsLinks_$(SourceBranchName)_$(Rev:r)

steps:
- template: Templates/step-execute-ci-tool.yaml
  parameters:
    tool: 'CheckLinks'
    toolArguments: '"DryWetMidi" "*.cs"'