trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/CI/run-static-analysis.yaml'

pr: none

variables:
- group: DryWetMIDI-Common-Variables

pool:
  vmImage: 'windows-latest'
  
name: RunStaticAnalysis_$(SourceBranchName)_$(LibraryVersion)$(Rev:.r)

stages:
- template: Templates/stage-build-native-libs.yaml
    
- stage: RunAnalyze
  displayName: Run analyze
  jobs:
  - job: RunReSharper
    displayName: Run ReSharper analysis
    steps:
    - template: Templates/step-copy-native-libraries-near-csproj.yaml
    
    - template: Templates/step-setup-framework.yaml
      parameters:
        framework: 'Net'
  
    - task: CmdLine@2
      displayName: Install tool
      inputs:
        script: 'dotnet tool install -g JetBrains.ReSharper.GlobalTools'
  
    - task: CmdLine@2
      displayName: Run analysis
      inputs:
        script: 'jb inspectcode Melanchall.DryWetMidi.sln --properties:Configuration=DebugTest --exclude="DryWetMidi.Benchmarks\**.*" -o=ReSharperReport.sarif'
    
    - task: DotNetCoreCLI@2
      displayName: Convert report to HTML
      inputs:
        command: 'run'
        projects: 'Resources/Utilities/ConvertReSharperReportToHtml/ConvertReSharperReportToHtml/ConvertReSharperReportToHtml.csproj'
        arguments: '-c Release -- ReSharperReport.sarif ReSharperReport.html $(Build.SourceBranchName)'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish 'ReSharperReport' artifact
      inputs:
        targetPath: ReSharperReport.html
        artifact: ReSharperReport