trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/CI/test-package-integration.yaml'
    - 'Resources/CI/Templates/stage-build-native-libs.yaml'
    - 'Resources/CI/Templates/step-create-ports-macos.yaml'
    - 'Resources/CI/Templates/step-create-ports-windows.yaml'
    - 'Resources/CI/Templates/job-build-package.yaml'
    - 'Resources/CI/Templates/step-setup-framework-variables.yaml'
    - 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/*'
    - 'Resources/Native/*'

pr: none

variables:
- group: DryWetMIDI-Common-Variables

name: TestPackageIntegration_$(SourceBranchName)_$(LibraryVersion)$(Rev:.r)

stages:
- template: Templates/stage-build-native-libs.yaml

- stage: BuildPackage
  displayName: Build package
  pool:
    vmImage: 'windows-latest'
  jobs:
  - template: Templates/job-build-package.yaml
    parameters:
      packageType: 'Full'

- stage: TestPackageIntegration
  displayName: Test package integration
  jobs:
  - job: TestPackageIntegration
    displayName: Test package integration
    strategy:
      matrix:
        Windows_Net:
          vmImage: 'windows-latest'
          framework: 'Net'
          rid: 'win-x64'
        macOS_Net:
          vmImage: 'macos-latest'
          framework: 'Net'
          rid: 'osx-x64'
        macOS_Arm_Net:
          vmImage: 'macOS-15-arm64'
          framework: 'Net'
          rid: 'osx-arm64'
        # TODO: check on Ubuntu without Multimedia API
        #Ubuntu_Net:
        #  vmImage: 'ubuntu-latest'
        #  framework: 'Net'
        #  rid: 'linux-x64'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download NuGet package
      inputs:
        source: 'current'
        path: '$(Pipeline.Workspace)\NuGetPackage'
        artifact: NuGetPackage
    
    - template: Templates/step-setup-framework.yaml
      parameters:
        framework: '$(framework)'
    
    - task: PowerShell@2
      displayName: Add package to the project
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Adding local NuGet source with the package..."
          dotnet nuget add source "$(Pipeline.Workspace)\NuGetPackage"
    
          Write-Host "Adding Melanchall.DryWetMidi.$(LibraryVersion) package reference to the project..."
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetConsoleApp\DwmNetConsoleApp\DwmNetConsoleApp.csproj'
          dotnet add "$path" package Melanchall.DryWetMidi -v $(LibraryVersion) -s "$(Pipeline.Workspace)\NuGetPackage"

    - task: PowerShell@2
      displayName: Check csproj package reference
      inputs:
        targetType: 'inline'
        script: |
          $path = Resolve-Path "Resources\PackageIntegrationTestUtilities\DwmNetConsoleApp\DwmNetConsoleApp\DwmNetConsoleApp.csproj"
          $expected = '<PackageReference Include="Melanchall.DryWetMidi" Version="$(LibraryVersion)" />'
          Write-Host "Expecting: $expected"
          $found = Select-String -Path $path -Pattern $expected -SimpleMatch -Quiet
          if (-not $found) {
            Write-Error "Package reference not found: $expected"
            exit 1
          }
          Write-Host "Package reference found."

    - template: Templates/step-create-ports-windows.yaml
      parameters:
        enabled: contains(variables.vmImage, 'windows')
    
    - template: Templates/step-create-ports-macos.yaml
      parameters:
        enabled: contains(variables.vmImage, 'macos')

    - task: DotNetCoreCLI@2
      displayName: Run app via dotnet
      inputs:
        command: 'run'
        projects: 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
        arguments: '--configuration $(BuildConfiguration) -property:SolutionDir="$(Build.SourcesDirectory)/"'

    - task: PowerShell@2
      displayName: Publish and run
      inputs:
        targetType: 'inline'
        script: |
          $projectPath = "Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj"
    
          foreach ($psf in @('true', 'false')) {
            foreach ($prtr in @('true', 'false')) {
              foreach ($inlfse in @('true', 'false')) {
                foreach ($sc in @('true', 'false')) {
                  foreach ($pt in @('true', 'false')) {
                    $publishOptions = @"
          SelfContained = $sc
          PublishSingleFile = $psf
          PublishReadyToRun = $prtr
          IncludeNativeLibrariesForSelfExtract = $inlfse
          PublishTrimmed = $pt
          "@
                    Write-Host "$publishOptions"

                    if (($pt -eq 'true' -and $sc -eq 'false') -or
                        ($sc -eq 'false' -and $inlfse -eq 'true') -or
                        ($prtr -eq 'true' -and $psf -eq 'true' -and $sc -eq 'false')) {
                      Write-Host "Invalid configuration; skipped."
                      continue;
                    }
                    
                    $outputPath = "$(Build.ArtifactStagingDirectory)/publish/$(rid)/sc-$sc-psf-$psf-prtr-$prtr-inlfse-$inlfse-pt-$pt"
                    Write-Host "Output path set to '$outputPath'"
                    
                    Write-Host "Publishing the app..."
                    dotnet publish `
                      --configuration $(BuildConfiguration) `
                      --runtime $(rid) `
                      --self-contained=$sc `
                      -p:PublishSingleFile=$psf `
                      -p:PublishReadyToRun=$prtr `
                      -p:IncludeNativeLibrariesForSelfExtract=$inlfse `
                      -p:PublishTrimmed=$pt `
                      -p:SolutionDir="$(Build.SourcesDirectory)/" `
                      --output $outputPath `
                      $projectPath
                    
                    if ($LASTEXITCODE -ne 0) {
                      Write-Error "Publish failed with exit code $LASTEXITCODE"
                      exit $LASTEXITCODE
                    }
                    
                    Write-Host "Listing published files..."
                    Write-Host ""
                    Get-ChildItem -Recurse -Force -Path "$outputPath" | Format-Table @{Label="File Name"; Expression={$_.Name}}, @{Label="Size (KB)"; Expression={"{0:N2}" -f ($_.Length / 1KB)}}
                    Write-Host ""
                    
                    Write-Host "Running the app..."
                    Write-Host ""
                    if ($IsWindows) {
                      & "$outputPath/DwmNetConsoleApp.exe"
                    } else {
                      & "$outputPath/DwmNetConsoleApp"
                    }
                    
                    if ($LASTEXITCODE -ne 0) {
                      Write-Error "App execution failed with exit code $LASTEXITCODE"
                      exit $LASTEXITCODE
                    }
                    
                    Write-Host ""
                    Write-Host "Configuration test completed successfully"
                    Write-Host ""
                  }
                }
              }
            }
          }