typedef int TG_STARTRESULT;

#define WINDOWS_TG_STARTRESULT_OK 0
#define WINDOWS_TG_STARTRESULT_CANTGETDEVICECAPABILITIES 1
#define WINDOWS_TG_STARTRESULT_CANTSETTIMERCALLBACK 2

typedef int TG_STOPRESULT;

#define WINDOWS_TG_STOPRESULT_OK 0
#define WINDOWS_TG_STOPRESULT_CANTENDPERIOD 1
#define WINDOWS_TG_STOPRESULT_CANTKILLEVENT 2