<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <Configurations>Debug;Release;ReleaseTest;ReleaseTestFull;ReleaseNativeless</Configurations>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>strongnamekey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG;TRACE;TEST;FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseNativeless'">
    <DefineConstants>NATIVELESS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseTest'">
    <DefineConstants>TEST;FULL</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseTestFull'">
    <DefineConstants>TRACE;TEST;FULL</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SendTestData.c" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DryWetMidi\Melanchall.DryWetMidi.csproj" />
  </ItemGroup>

  <ItemGroup Label="Nativeless" Condition="'$(Configuration)'=='ReleaseNativeless'">
    <Compile Remove="Multimedia\**\*.cs" />
  </ItemGroup>

  <Import Project="$(SolutionDir)Melanchall.DryWetMidi.Native.targets" />

</Project>
