name: Build Native Libraries

on: 
  workflow_call:

jobs:
  build-dll-x64:
    name: Build x64 dll
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses:  actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore NuGet packages
        run: |
          nuget restore "Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj" -SolutionDirectory "${{ github.workspace }}/Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows"

      - name: Build dll
        run: |
          msbuild Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:SolutionDir="${{ github.workspace }}\Resources\Native\Windows\Melanchall.DryWetMidi.Native.Windows\"
        shell: pwsh
      
      - name:  Upload dll artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Native_Win_x64
          path: Resources/Native/Windows/Melanchall_DryWetMidi_Native.dll
          if-no-files-found: error
          
  build-dll-arm64:
    name: Build arm64 dll
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses:  actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore NuGet packages
        run: |
          nuget restore "Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj" -SolutionDirectory "${{ github.workspace }}/Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows"

      - name: Build dll
        run: |
          msbuild Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj `
            /p:Configuration=Release `
            /p:Platform=ARM64EC `
            /p:SolutionDir="${{ github.workspace }}\Resources\Native\Windows\Melanchall.DryWetMidi.Native.Windows\"
        shell: pwsh
      
      - name:  Upload dll artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Native_Win_arm64
          path: Resources/Native/Windows/Melanchall_DryWetMidi_Native.dll
          if-no-files-found: error

  build-dylib-x64-arm64:
    name: Build x64/arm64 dylib
    runs-on: macos-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v4
      
      - name: Build dylib
        shell: pwsh
        run: |
          cd Resources/Native/macOS
          Write-Host "Building arm64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native_arm64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch arm64
          Write-Host "Building x64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native_x86_64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch x86_64
          Write-Host "Merging dylibs..."
          lipo Melanchall_DryWetMidi_Native_x86_64.dylib Melanchall_DryWetMidi_Native_arm64.dylib -output Melanchall_DryWetMidi_Native.dylib -create
          Write-Host "Printing architectures..."
          lipo -info Melanchall_DryWetMidi_Native.dylib
      
      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: Native_macOS_x64_arm64
          path: Resources/Native/macOS/Melanchall_DryWetMidi_Native.dylib
          if-no-files-found: error