name: Build NuGet Package

on:
  workflow_call:
    inputs:
      package-type:
        description: 'Package type (Full or Nativeless)'
        required: false
        type: string
        default: 'Full'

jobs:
  build-package: 
    name: Build NuGet Package
    runs-on: windows-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v4
      
      - name: Download native libraries
        if: inputs.package-type == 'Full'
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/NativeLibraries
      
      - name: Setup metadata
        shell: pwsh
        run: |
          $filePath = Resolve-Path "DryWetMidi/Melanchall.DryWetMidi.csproj"
          $xml = New-Object xml
          $xml.PreserveWhitespace = $true
          $xml.Load($filePath)
          
          $version = $xml.Project.PropertyGroup[1].Version
          Write-Host "Current version is $version"
          $newVersion = "${{ vars.LIBRARY_VERSION }}"
          $xml.Project.PropertyGroup[1].Version = $newVersion
          Write-Host "New version: $($xml.Project.PropertyGroup[1].Version)"
          
          Write-Host "Setting release notes up..."
          $xml.Project.PropertyGroup[1].PackageReleaseNotes = "https://github.com/melanchall/drywetmidi/releases/tag/v${{ vars.LIBRARY_VERSION }}"
          Write-Host "Release notes: $($xml.Project.PropertyGroup[1].PackageReleaseNotes)"
          
          Write-Host "Setting copyright up..."
          $xml.Project.PropertyGroup[1].Copyright = "Copyright © Melanchall $((Get-Date).Year)"
          Write-Host "Copyright: $($xml.Project.PropertyGroup[1].Copyright)"
          
          $xml.Save($filePath)
      
      - name: Setup framework
        id: framework
        uses: ./.github/actions/setup-framework
        with:
          framework:  Net
          net-tfm:  ${{ vars.BUILD_FRAMEWORK_NET_TFM || 'net8.0' }}
          net-sdk-version: ${{ vars.BUILD_FRAMEWORK_NET_SDK_VERSION || '8.0.x' }}
          netframework-tfm: ${{ vars.BUILD_FRAMEWORK_NETFRAMEWORK_TFM || 'net48' }}
          netframework-sdk-version: ${{ vars.BUILD_FRAMEWORK_NETFRAMEWORK_SDK_VERSION || '8.0.x' }}
      
      - name: Setup nativeless project
        if: inputs.package-type == 'Nativeless'
        shell: pwsh
        run: |
          $encoding = [System.Text.Encoding]::UTF8
          $filePath = Resolve-Path "DryWetMidi\Melanchall.DryWetMidi.csproj"
          $csproj = [xml]([System.IO.File]::ReadAllText($filePath, $encoding))
      
          Write-Host "Setting package metadata values..."        
          $packageGroup = (Select-Xml -Xml $csproj.Project -XPath "//*[@Label='Package']").Node
          Write-Host "Current 'Package' group:"
          Write-Host ($packageGroup | Format-Table | Out-String)
          $packageGroup.PackageId = "Melanchall.DryWetMidi.Nativeless"
          $description = $packageGroup.Description
          $readmeNode = (Select-Xml -Xml $packageGroup -XPath "//PackageReadmeFile").Node
          $packageGroup.RemoveChild($readmeNode)
          Write-Host "New 'Package' group:"
          Write-Host ($packageGroup | Format-Table | Out-String)
                  
          $nativeGroup = (Select-Xml -Xml $csproj.Project -XPath "//*[@Label='Native']").Node
          Write-Host "'Native' group will be removed:"
          Write-Host ($nativeGroup | Format-Table | Out-String)
          $csproj.Project.RemoveChild($nativeGroup)
      
          Write-Host "Removing README pack instruction..."
          $resourcesGroup = (Select-Xml -Xml $csproj.Project -XPath "//*[@Label='Resources']").Node
          Write-Host "'Resources' group:"
          Write-Host ($resourcesGroup | Format-Table | Out-String)
          $readmeNode = (Select-Xml -Xml $resourcesGroup -XPath "//*[contains(@Include,'README')]").Node
          Write-Host "'README' node:"
          Write-Host ($readmeNode | Format-Table | Out-String)
          $resourcesGroup.RemoveChild($readmeNode)
                  
          $csproj.Save($filePath)
      
          Write-Host "Setting icon path..."
          (Get-Content $filePath) -replace 'icon.png', 'icon-nativeless.png' | Set-Content $filePath

      - name: Copy native libraries locally
        if: inputs.package-type == 'Full'
        shell: pwsh
        run: |
          & "${{ github.workspace }}/Resources/Scripts/Copy native binaries locally.ps1" -fromDirectory "${{ runner.temp }}/NativeLibraries"
      
      - name: Build project
        run: dotnet build DryWetMidi/Melanchall.DryWetMidi.csproj --configuration ${{ vars.BUILD_CONFIGURATION || 'Release' }}
      
      - name: Create NuGet package
        run:  |
          dotnet pack DryWetMidi/Melanchall.DryWetMidi.csproj `
            --no-build `
            --configuration ${{ vars.BUILD_CONFIGURATION || 'Release' }} `
            --output NuGetPackage `
            -p:RepositoryBranch="${{ github.ref_name }}"
      
      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackage
          path:  NuGetPackage/*.nupkg
          if-no-files-found: error