name: Build Native Libraries

on: 
  workflow_call:

jobs:
  build-dll:
    name: Build ${{ matrix.platform }} dll
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - platform: x64
            artifact_name: Native_Win_x64
          - platform: ARM64EC
            artifact_name: Native_Win_arm64
    steps:
      - name: Checkout
        uses:  actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Download Microsoft.Windows.Devices.Midi2.nupkg
        shell: pwsh
        run: |
          $packageUrl = "https://github.com/microsoft/MIDI/releases/download/inbox-dev-preview-1/Windows.Devices.Midi2.0.99.30-devpreview.1.nupkg"
          $downloadFolder = "${{ runner.temp }}\Midi2"
          
          New-Item -Path $downloadFolder -ItemType Directory -Force | Out-Null
          
          $fileName = Split-Path $packageUrl -Leaf
          $destinationPath = Join-Path $downloadFolder $fileName
          
          Write-Host "Downloading package from: $packageUrl"
          Write-Host "Saving to: $destinationPath"
          
          Invoke-WebRequest -Uri $packageUrl -OutFile $destinationPath
          Write-Host "Download complete. Package saved to: $destinationPath"

      - name: Restore NuGet packages
        run: |
          nuget restore "Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj" -Source "${{ runner.temp }}\Midi2" -Source "https://api.nuget.org/v3/index.json" -SolutionDirectory "${{ github.workspace }}/Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows"

      - name: Download Microsoft.Windows.Devices.Midi2.nupkg
        shell: pwsh
        run: |
          $packageRuntimesDir = "${{ github.workspace }}\Resources\Native\Windows\Melanchall.DryWetMidi.Native.Windows\packages\Windows.Devices.Midi2.0.99.30-devpreview.1\runtimes"
          $srcFolder = "$packageRuntimesDir\win-arm64"
          $dstFolder = "$packageRuntimesDir\win-ARM64EC"
        
          Write-Host "Checking paths..."
          if (Test-Path $srcFolder) {
            if (-not (Test-Path $dstFolder)) {
                New-Item -ItemType Junction -Path $dstFolder -Value $srcFolder
                Write-Host "Successfully linked $srcFolder to $dstFolder"
            } else {
                Write-Host "Destination folder already exists."
            }
          } else {
            Write-Error "Source folder $srcFolder not found! Make sure NuGet restore step has completed successfully."
          }

      - name: Build dll
        run: |
          msbuild Resources/Native/Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows/Melanchall.DryWetMidi.Native.Windows.vcxproj `
            /p:Configuration=Release `
            /p:Platform=${{ matrix.platform }} `
            /p:SolutionDir="${{ github.workspace }}\Resources\Native\Windows\Melanchall.DryWetMidi.Native.Windows\"
        shell: pwsh
      
      - name:  Upload dll artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ matrix.artifact_name }}
          path: Resources/Native/Windows/Melanchall_DryWetMidi_Native.dll
          if-no-files-found: error

  build-dylib-x64-arm64:
    name: Build x64/arm64 dylib
    runs-on: macos-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v4
      
      - name: Build dylib
        shell: pwsh
        run: |
          cd Resources/Native/macOS
          Write-Host "Building arm64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native_arm64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch arm64
          Write-Host "Building x64 dylib..."
          clang -shared -undefined dynamic_lookup -o Melanchall_DryWetMidi_Native_x86_64.dylib NativeApi-macOS.cpp -framework CoreServices -framework CoreFoundation -framework CoreMIDI -arch x86_64
          Write-Host "Merging dylibs..."
          lipo Melanchall_DryWetMidi_Native_x86_64.dylib Melanchall_DryWetMidi_Native_arm64.dylib -output Melanchall_DryWetMidi_Native.dylib -create
          Write-Host "Printing architectures..."
          lipo -info Melanchall_DryWetMidi_Native.dylib
      
      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: Native_macOS_x64_arm64
          path: Resources/Native/macOS/Melanchall_DryWetMidi_Native.dylib
          if-no-files-found: error