name: Test .NET Package Integration

run-name: TestPackageIntegration_Net_${{ github.ref_name }}_${{ vars.LIBRARY_VERSION }}_${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - develop
    paths: 
      - 'DryWetMidi/**'
      - '.github/workflows/test-net-package-integration.yml'
      - '.github/workflows/build-native-libs.yml'
      - '.github/workflows/build-package.yml'
      - '.github/actions/**'
      - 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/**'
      - 'Resources/Native/**'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress:  true

jobs:
  build-native-libs:
    name: Build Native Libraries
    uses: ./.github/workflows/build-native-libs.yml
  
  build-package:
    name: Build NuGet Package
    needs: build-native-libs
    uses: ./.github/workflows/build-package.yml
    secrets: inherit

  test-package-integration: 
    name: Test package integration (${{ matrix.os }})
    needs: build-package
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: 
        include:
          #- os: windows-11-arm
          #  framework: Net
          - os: macos-latest
            framework: Net
    
    steps:
      - name:  Checkout
        uses: actions/checkout@v4
      
      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with: 
          name: NuGetPackage
          path: NuGetPackage
      
      - name: Setup framework
        id: framework
        uses: ./.github/actions/setup-framework
        with:
          framework: ${{ matrix.framework }}
          net-tfm: ${{ vars.BUILD_FRAMEWORK_NET_TFM || 'net8.0' }}
          net-sdk-version: ${{ vars.BUILD_FRAMEWORK_NET_SDK_VERSION || '8.0.x' }}
          netframework-tfm:  ${{ vars.BUILD_FRAMEWORK_NETFRAMEWORK_TFM || 'net48' }}
          netframework-sdk-version:  ${{ vars.BUILD_FRAMEWORK_NETFRAMEWORK_SDK_VERSION || '8.0.x' }}
      
      - name:  Create MIDI ports (Windows)
        if: runner.os == 'Windows'
        uses: ./.github/actions/create-ports-windows
        with:
          enabled: 'true'
          ports-names: 'MIDI A,MIDI B,MIDI C'
      
      - name: Create MIDI ports (macOS)
        if: runner.os == 'macOS'
        uses: ./.github/actions/create-ports-macos
        with:  
          enabled: 'true'
      
      - name:  Add package to the project
        shell: pwsh
        run: |
          $path = Resolve-Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          dotnet add "$path" package Melanchall.DryWetMidi -v ${{ vars.LIBRARY_VERSION }} -s "${{ github.workspace }}/NuGetPackage"
      
      - name: Set csproj elements
        shell:  pwsh
        run: |
          Write-Host "Parsing csproj..."
          [xml]$xml = Get-Content -Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          
          Write-Host "Setting TFM ${{ steps.framework.outputs.tfm }}..."
          $xml.Project.PropertyGroup.TargetFramework = '${{ steps.framework.outputs.tfm }}'
          
          Write-Host "Saving csproj..."
          $path = Resolve-Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          $xml.Save($path)
          
          Write-Host "Displaying csproj content..."
          $content = Get-Content -Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          Write-Host $content
      
      - name: Restore packages
        shell: pwsh
        run: |
          $path = Resolve-Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          dotnet nuget add source "${{ github.workspace }}/NuGetPackage"
          dotnet restore "$path"
      
      - name: Run test program
        shell: pwsh
        run: |
          $path = Resolve-Path 'Resources/PackageIntegrationTestUtilities/DwmNetConsoleApp/DwmNetConsoleApp/DwmNetConsoleApp.csproj'
          dotnet run --project "$path" --no-restore